matrix:
  include:
    - language: python
      dist: bionic
      python: 3.6
      script:
        - pip install breathe

    - language: cpp
      dist: bionic

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

install:
  - pip install breathe

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
