language: cpp
dist: bionic

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

install:
  - pip install breathe

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
